version: "3.9"


# Declare new services
services:
  
  server:
    build:
      context: ../..  # Should be aioquic
      dockerfile: ./examples/control_test/server.Dockerfile
    networks:
      test1-net:
        ipv6_address: 2001:db8:1::10
        aliases:  # set hostname
          - server
    ports:
      - "4433"
      - "8081" # extra open port for testing
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
  
  client:
    build:
      context: ../..  # Should be aioquic
      dockerfile: ./examples/control_test/client.Dockerfile
    networks:
      test1-net:
        ipv6_address: 2001:db8:1::11
    ports:
      - "4433"
      - "8081" # extra open port for testing
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0


# Declare new networks
# docker network create --subnet=172.16.2.0/24 --gateway=172.16.2.1 --ipv6 --subnet=2001:db8:1::/64 --opt com.docker.network.bridge.enable_ip_masquerade=true test1-net
networks:
#  test1-net:
#    name: test1-net
#    driver: bridge
#    driver_opts:
#      com.docker.network.enable_ipv6: "true"
#    external: false
#    ipam:
#      driver: default
#      config:
#        - subnet: 2001:db8:1::/64
#          gateway: 2001:db8:1::1
  test1-net:
    name: test1-net
    external: true

